### ISSUE TITLE
Collapse if asked to display a list with cycles

### ISSUE THREAD

**Issue by Lixinyi-DUT** [Cal-CS-61A-Staff/dart_scheme#70]
```scm
(define n3 (list 'c))
(define n2 (cons 'b n3))
(define w (cons 'a n2))
(set-cdr! n3 w)
```
When typing commands such as `display w` or even just `w`, it falls into a dead cycle without any response.

The problem may be solved by introduce '#n#' notation as what DrRacket does. So the list can be represented as `#0=(a b c . #0#)`.

**Comment by jathak** [comment]
We've considered alternate displays of promises and streams in #43, but rejected it to avoid confusing students with new syntax. I'm rejecting this for the same reason.

In the past, displaying a list with a cycle would stall the interpreter, but we've since changed the list display function to be recursive, so we now get a stack overflow instead, which I believe is acceptable.

To inspect the structure of a cyclic list, use the box-and-pointer diagrammer by passing the list to the `draw` built-in procedure.
